language: rust
cache: cargo
rust:
- stable
- beta
- nightly

os:
- linux
- osx

env:
  global:
    - secure: "llTyX5P3hSaYYYIhmT7YlceqmfoeluB4rR9JMp8pkMPUeDBc7YPlULTfalpSxOlFCGLtNit1qVcPEIrm80tAzknDYMXWHHvVu4wcVCWMdeShwFFKlPqZJwIkEH/tGlUP+k49KIFOV4gvwOfUo7d1cg9garOnlGZW+z1RU2rQMUgu0QaQrNoux24HOenNfYnMGfGTHUFuyz9WXtU7yw6fUOr/VUiqc6BBndu1ip+WgM71btK9gdbbB4Qy/GP0IaP3lhZ+AqtKtugOzEtdXhs5QJvyWDdQqq4jzDi8R+tc2VVKhomiTADQBHTKV/P8uZhHoclA6D+2TOeqX3k/5nfS9hcKBzOe5wIiVkmXf1/bxJpliF/7YnB1zSFnrKHAS4LU1jdHPMu8VRyQZ3EUoaCOW9WxL87LP489V4j2LZrIV9fOmgstlS8MZGcXDnqaUqoaOf78tcYwBtblcMsQj4ANktySv7SDLTTx5UEXfecX8W7nEdvggOcfzEqMR4k13pZeZ4AFmI7p2Za0BeaOl3vayaAv3Y4hlCM9AabutLOaRGODV3Jra1PlPGzaDc4TtYFAxyoOx/4KVeKs0sw9lFgd93V6TWfhqbZ/n6HXEREQb/UVtt4YAtO9IW1gDOYzFXt3Fh9Hwt8ZB0vHHfRHuw/EC5+WcfLqstBqeosjlH/C+wg="

notifications:
  email:
    on_success: never

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev bats; else brew install libusb bats; fi
- travis_wait cargo install rustfmt --force || true

before_script:
- export PATH="$PATH":~/.cargo/bin
- echo "\$ rustfmt --version"
- cargo fmt --all -- --version

script:
# Install Janus
- curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
# Add Janus to PATH.
- export PATH=$PATH:$PWD/janusbin
- export APP_VERSION="$(janus version -format 'v%M.%m.%C-%S')"
- export RUST_BACKTRACE=1
- cargo fmt --all -- --verbose --write-mode=diff
- cargo test --all --verbose
- cargo build --all --verbose --release
# Copy build to default cargo bin path for bats tests.
- cp ./target/release/emerald "$HOME/.cargo/bin/"
- bats cli.bats

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
  tags: true
