language: rust
cache: cargo
rust:
- stable
- beta
- nightly

os:
- linux
- osx

env:
  global:
    - secure: "uCQd8E9KPdefmbnQw4MfklO0DTeL/B6UyFjnk1s0MevVU0/sDfuQARUS7kALaEsgyRjiWKwU1qnmEQkW0nFLR1GMGPhnIOjfUBlPbW0xv7cn1VihXZgJ2+rzpYgPC5b+Av56xVBPpfHBANpraLCTIjjjR03EvoZeZlCD+6ElcN3XH8CHYyp5+Dsblv61WRIfbIy5NCBWTQ1A9iBBk1kx3z363SqO8DsK0AF/rmGZwFRog8mLZBsE4XKtUwLtdC0qVyg39MFSTiH17QkznB2Ctf4Awxvp3+AJLrhCYbmy08iOkPpkjmMevqFMElPL1F5KbqL5aRYxpazU48hKQTOuBGuvMd/xsktRCfOBXbnGwO70Mpd3HXuJGjy4wkfrO+ecnj6KS2oEqOyFjtLLicrSr4QSGu8vSBd3iwxyoEgwDf0neFrazCiaXzkI8YDfZtYM3UIATnrCyRVMeYPVXnb9QuLOBjEdT56PEyD+kbtutc0jn/pzBryH6FmgguZqndC3xTu5cgoxIuFo+qIDjSxsDCcY3oPxX9hqOXjcTWEEnqAbW46NhZmtumJ+ocER5J9vHr99J9FMjaNCcL6nmosyxJ6IXInAjgF1lbhZhm2Pb8kkCZBF1WWFpEqbg4xGGnGB/bUd4hLuM9AWcAK18B2Le/5XF5cXSHkHJMx73ABA2HQ="

notifications:
  email:
    on_success: never

before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi
- travis_wait cargo install rustfmt --force || true

before_script:
- export PATH="$PATH":~/.cargo/bin
- echo "\$ rustfmt --version"
- cargo fmt --all -- --version

script:
# Install Janus
- curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
# Add Janus to PATH.
- export PATH=$PATH:$PWD/janusbin

- export RUST_BACKTRACE=1
- cargo fmt --all -- --verbose --write-mode=diff
- cargo test --all --verbose
- cargo build --all --verbose --release

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: issue/ci_builds
  tags: true
