[package]
name = "emerald-cli"
version = "0.1.0"
authors = ["Constantine Kryvomaz <kostiyantynk@gmail.com>"]
description = "Console utility for secure account management"
homepage = "http://etcdevteam.com"
repository = "https://github.com/ethereumproject/emerald-cli"
documentation = "https://docs.rs/emerald-cli"
keywords = ["ethereum-classic", "blockchain", "ffi", "crypto-wallet", "cold-storage", "cli"]
categories = ["cli", "script"]
readme = "../README.adoc"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "ethereumproject/emerald-cli" }
appveyor = { repository = "ethereumproject/emerald-cli" }

[[bin]]
name = "emerald"
path = "src/main.rs"

[dependencies]
log = "0.3"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
env_logger = { version = "0.4", optional = true }
emerald-core = { git = "https://github.com/r8d8/emerald-rs", branch = "feature/cli_interface" }
#emerald-core = { path = "../emerald-rs/emerald-core"}
regex = "0.2"
rustc-serialize = "0.3"
clippy = {version = "0.0", optional = true}

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"
# quickcheck_macros = "0.4"

[features]
default = ["cli"]
cli = ["env_logger"]
dev = ["clippy"]
