version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Install software
          command: |
              curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
              brew install bats
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
              rustc -V

#      - run:
#          name: Tests
#          command: |


      - run:
          name: Build
          command: |
              export PATH=$PATH:$PWD/janusbin
              export APP_VERSION_GIT_TAG="$(janus version -format 'TAG_OR_NIGHTLY')"
              echo "Building app version $APP_VERSION_GIT_TAG"
              cargo build --all --verbose --release
              cp ./target/release/emerald "$HOME/.cargo/bin/"
              bats cli.bats

      - deploy:
          name: Deploy to builds.etcdevteam.com
          command: |
              export PATH=$PATH:$PWD/janusbin
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  .circleci/deploy.sh
              fi